"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_1)\
$os\
$username\
[](bg:color_2 fg:color_1)\
$directory\
[](fg:color_2 bg:color_3)\
$git_branch\
$git_status\
[](fg:color_3 bg:color_4)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_4 bg:color_bg3)\
$docker_context\
[](fg:color_bg3 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#400406'
color_1 = '#4a4a48'
color_2 = '#566246'
color_3 = '#a4c2a5'
color_4 = '#d8dad3'
color_5 = '#f1f2eb'

#color_4 = '#458588'
#color_3 = '#689d6a'
color_green = '#98971a'
#color_1 = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
#color_2 = '#d79921'

[os]
disabled = false
style = "bg:color_1 fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_1 fg:color_fg0"
style_root = "bg:color_1 fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_2"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_3"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_3)]($style)'

[git_status]
style = "bg:color_3"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_3)]($style)'

[nodejs]
symbol = ""
style = "bg:color_4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_4)]($style)'

[c]
symbol = " "
style = "bg:color_4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_4)]($style)'

[rust]
symbol = ""
style = "bg:color_4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_4)]($style)'

[golang]
symbol = ""
style = "bg:color_4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_4)]($style)'

[php]
symbol = ""
style = "bg:color_4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_4)]($style)'

[java]
symbol = " "
style = "bg:color_4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_4)]($style)'

[kotlin]
symbol = ""
style = "bg:color_4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_4)]($style)'

[haskell]
symbol = ""
style = "bg:color_4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_4)]($style)'

[python]
symbol = ""
style = "bg:color_4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_4)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_2)'
